kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-tasks
    spec:
      containers:
      - name: demo-job-container
        image: busybox:latest
        command: ["sh", "-c", "echo 'Hello, munna!' && sleep 10"]
      restartPolicy: Never